import 'package:flutter/material.dart';
import '../core/widgets.dart';
import 'registration.dart';

class OnboardingScreen extends StatefulWidget {
  const OnboardingScreen({super.key});
  @override State<OnboardingScreen> createState()=>_OnboardingScreenState();
}
class _OnboardingScreenState extends State<OnboardingScreen>{
  final PageController pc=PageController(); int index=0; bool location=true,updates=true;
  @override Widget build(BuildContext context)=>Scaffold(body:SafeArea(child:Column(children:[
    Padding(padding:const EdgeInsets.fromLTRB(20,14,20,4),child:const Row(children:[Expanded(child:ZenjiLogo(height:54)),ThemeLanguageRow()])),
    Expanded(child:PageView(controller:pc,onPageChanged:(v)=>setState(()=>index=v),children:[_about(),_permissions()])),
    Padding(padding:const EdgeInsets.fromLTRB(20,8,20,22),child:Column(children:[Row(mainAxisAlignment:MainAxisAlignment.center,children:List.generate(2,(i)=>AnimatedContainer(duration:const Duration(milliseconds:250),margin:const EdgeInsets.symmetric(horizontal:4),width:index==i?28:8,height:8,decoration:BoxDecoration(color:index==i?Theme.of(context).colorScheme.primary:Theme.of(context).colorScheme.onSurface.withValues(alpha:.18),borderRadius:BorderRadius.circular(99))))),const SizedBox(height:16),LoadingButton(label:index==0?'Continue':'Allow & continue',icon:Icons.arrow_forward_rounded,onPressed:()async{await fakeDelay(350);if(index==0){pc.nextPage(duration:const Duration(milliseconds:350),curve:Curves.easeOut);}else{if(context.mounted)Navigator.pushReplacement(context,MaterialPageRoute(builder:(_)=>const RegistrationScreen()));}})]))
  ])));
  Widget _about()=>ResponsivePage(child:Column(children:[const SizedBox(height:28),Container(width:92,height:92,decoration:BoxDecoration(color:Theme.of(context).colorScheme.primary.withValues(alpha:.12),shape:BoxShape.circle),child:Icon(Icons.local_taxi_rounded,size:48,color:Theme.of(context).colorScheme.primary)),const SizedBox(height:28),Text('Drive with ZenjiGO',style:Theme.of(context).textTheme.headlineMedium?.copyWith(fontWeight:FontWeight.w900),textAlign:TextAlign.center),const SizedBox(height:14),Text('ZenjiGO connects trusted drivers with riders across Zanzibar and Tanzania. Earn on your schedule, receive nearby ride requests, track trips live, manage earnings, and get support in one professional driver app.',textAlign:TextAlign.center,style:TextStyle(height:1.55,fontSize:16,color:Theme.of(context).colorScheme.onSurface.withValues(alpha:.72))),const SizedBox(height:28),Wrap(spacing:10,runSpacing:10,alignment:WrapAlignment.center,children:const[Pill('Flexible driving',icon:Icons.schedule),Pill('Secure earnings',icon:Icons.account_balance_wallet_outlined),Pill('Driver support',icon:Icons.support_agent)])]));
  Widget _permissions()=>ResponsivePage(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const SizedBox(height:20),Text('Permissions',style:Theme.of(context).textTheme.headlineMedium?.copyWith(fontWeight:FontWeight.w900)),const SizedBox(height:8),Text('These permissions help ZenjiGO work properly while you drive.',style:TextStyle(color:Theme.of(context).colorScheme.onSurface.withValues(alpha:.68))),const SizedBox(height:24),_permission(Icons.location_on_outlined,'Location permission','Required for nearby requests, navigation and live ride tracking.',location,(v)=>setState(()=>location=v)),const SizedBox(height:12),_permission(Icons.notifications_active_outlined,'Updates & offers','Receive ride activity, driver announcements, bonuses and offers.',updates,(v)=>setState(()=>updates=v)),const SizedBox(height:18),Card(child:Padding(padding:const EdgeInsets.all(16),child:Row(crossAxisAlignment:CrossAxisAlignment.start,children:[Icon(Icons.privacy_tip_outlined,color:Theme.of(context).colorScheme.primary),const SizedBox(width:12),Expanded(child:Text('You can change optional notification preferences later in Settings. Location is required when going online.',style:TextStyle(height:1.45,color:Theme.of(context).colorScheme.onSurface.withValues(alpha:.72))))]))) ]));
  Widget _permission(IconData icon,String title,String text,bool value,ValueChanged<bool> cb)=>Card(child:SwitchListTile(value:value,onChanged:title.startsWith('Location')?(v){setState(()=>location=true);toast(context,'Location is required for driver services.');}:cb,secondary:CircleAvatar(backgroundColor:Theme.of(context).colorScheme.primary.withValues(alpha:.12),child:Icon(icon,color:Theme.of(context).colorScheme.primary)),title:Text(title,style:const TextStyle(fontWeight:FontWeight.w800)),subtitle:Padding(padding:const EdgeInsets.only(top:4),child:Text(text))));
}
