import 'package:flutter/material.dart';
import '../core/app_state.dart';
import '../core/theme.dart';
import '../core/widgets.dart';
import 'chat.dart';

class ProfileScreen extends StatelessWidget {
  const ProfileScreen({super.key});
  @override Widget build(BuildContext context){final s=AppScope.of(context);return SafeArea(child:ListView(padding:const EdgeInsets.all(18),children:[
    Row(children:[Expanded(child:Text('Profile',style:Theme.of(context).textTheme.headlineSmall?.copyWith(fontWeight:FontWeight.w900))),IconButton.filledTonal(onPressed:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>const SettingsScreen())),icon:const Icon(Icons.settings_outlined))]),const SizedBox(height:14),
    Card(child:Padding(padding:const EdgeInsets.all(18),child:Column(children:[const CircleAvatar(radius:42,child:Icon(Icons.person,size:48)),const SizedBox(height:12),Text('Hassan Ali',style:Theme.of(context).textTheme.titleLarge?.copyWith(fontWeight:FontWeight.w900)),const SizedBox(height:4),const Text('ZenjiGO Driver • ZG-DRV-01842'),const SizedBox(height:10),const Row(mainAxisAlignment:MainAxisAlignment.center,children:[Pill('ACTIVE',color:ZenjiColors.green,icon:Icons.verified),SizedBox(width:8),Pill('★ 4.9',color:ZenjiColors.darkHighlight)])]))),
    const SizedBox(height:18),const SectionTitle('Driver account'),_tile(context,Icons.person_outline,'Personal & vehicle details','View all verified profile information',()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>const DriverDetailsScreen()))),_tile(context,Icons.star_outline,'Ratings & reviews','4.9 average • 238 reviews',()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>const ReviewsScreen()))),_tile(context,Icons.description_outlined,'Documents','License, ID, insurance and vehicle photos',()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>const DocumentsScreen()))),
    const SizedBox(height:18),const SectionTitle('Preferences & safety'),_tile(context,Icons.language,'Language',s.isSwahili?'Kiswahili':'English',()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>const SettingsScreen()))),_tile(context,Icons.emergency_outlined,'Emergency & support','Police and ZenjiGO contact options',()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>const EmergencyScreen()))),_tile(context,Icons.help_outline,'Help & support','Chat with ZenjiGO support',()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>const ChatScreen(name:'ZenjiGO Support',support:true)))),const SizedBox(height:20),Text('ZenjiGO Driver • Frontend demo',textAlign:TextAlign.center,style:TextStyle(fontSize:12,color:Theme.of(context).colorScheme.onSurface.withValues(alpha:.45))),const SizedBox(height:12)
  ]));}
  Widget _tile(BuildContext c,IconData i,String t,String s,VoidCallback tap)=>Card(margin:const EdgeInsets.only(bottom:9),child:ListTile(onTap:tap,leading:CircleAvatar(backgroundColor:Theme.of(c).colorScheme.primary.withValues(alpha:.12),child:Icon(i,color:Theme.of(c).colorScheme.primary)),title:Text(t,style:const TextStyle(fontWeight:FontWeight.w800)),subtitle:Text(s),trailing:const Icon(Icons.chevron_right)));
}

class DriverDetailsScreen extends StatelessWidget{const DriverDetailsScreen({super.key});@override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('Driver details')),body:ResponsivePage(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Card(child:Padding(padding:const EdgeInsets.all(16),child:Column(children:const[KeyValueRow('Full name','Hassan Ali'),KeyValueRow('Phone','+255 712 345 678'),KeyValueRow('Email','hassan@example.com'),KeyValueRow('Driver ID','ZG-DRV-01842'),KeyValueRow('Address','Mombasa, Zanzibar')]))),const SizedBox(height:14),const SectionTitle('Vehicle'),Card(child:Padding(padding:const EdgeInsets.all(16),child:Column(children:const[KeyValueRow('Type','Taxi'),KeyValueRow('Vehicle','Toyota Premio'),KeyValueRow('Plate no.','Z 123 ABC'),KeyValueRow('Color','White'),KeyValueRow('Model year','2021')]))),const SizedBox(height:18),Card(child:ListTile(leading:const Icon(Icons.info_outline),title:const Text('Profile changes require admin verification'),subtitle:const Text('Drivers cannot directly edit verified identity or vehicle information. Submit a request with the new value and reason.'))),const SizedBox(height:14),LoadingButton(label:'Request profile change',icon:Icons.edit_note,onPressed:()async{await fakeDelay(300);if(context.mounted)Navigator.push(context,MaterialPageRoute(builder:(_)=>const ProfileChangeRequestScreen()));})])));}

class ProfileChangeRequestScreen extends StatefulWidget{const ProfileChangeRequestScreen({super.key});@override State<ProfileChangeRequestScreen> createState()=>_ProfileChangeRequestScreenState();}
class _ProfileChangeRequestScreenState extends State<ProfileChangeRequestScreen>{String field='Phone';final key=GlobalKey<FormState>();@override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('Request profile change')),body:ResponsivePage(child:Form(key:key,child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('Admin verification required',style:Theme.of(context).textTheme.titleLarge?.copyWith(fontWeight:FontWeight.w900)),const SizedBox(height:8),Text('Your current profile stays unchanged until ZenjiGO reviews and approves this request.',style:TextStyle(color:Theme.of(context).colorScheme.onSurface.withValues(alpha:.66))),const SizedBox(height:20),DropdownButtonFormField<String>(initialValue:field,items:['Full name','Phone','Email','Vehicle type','Vehicle plate no.','Vehicle make / model','Address'].map((e)=>DropdownMenuItem(value:e,child:Text(e))).toList(),onChanged:(v)=>setState(()=>field=v!),decoration:const InputDecoration(labelText:'Information to change')),const SizedBox(height:14),TextFormField(validator:(v)=>(v==null||v.trim().isEmpty)?'New information is required':null,decoration:InputDecoration(labelText:'New $field')),const SizedBox(height:14),TextFormField(maxLines:4,validator:(v)=>(v==null||v.trim().isEmpty)?'Reason is required':null,decoration:const InputDecoration(labelText:'Reason for change')),const SizedBox(height:18),LoadingButton(label:'Submit request',icon:Icons.send_outlined,onPressed:()async{if(!(key.currentState?.validate()??false))return;await fakeDelay();if(!context.mounted)return;await showDialog(context:context,builder:(d)=>AlertDialog(icon:const Icon(Icons.schedule_send,size:42,color:ZenjiColors.green),title:const Text('Request sent'),content:const Text('ZenjiGO admin will verify the request. Approved changes will automatically reflect on your profile.'),actions:[FilledButton(onPressed:()=>Navigator.pop(d),child:const Text('Done'))]));if(context.mounted)Navigator.pop(context);})]))));}

class ReviewsScreen extends StatelessWidget{const ReviewsScreen({super.key});@override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('Ratings & reviews')),body:ListView(padding:const EdgeInsets.all(18),children:[Card(child:Padding(padding:const EdgeInsets.all(18),child:Row(children:[Text('4.9',style:Theme.of(context).textTheme.displaySmall?.copyWith(fontWeight:FontWeight.w900)),const SizedBox(width:16),const Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('★★★★★',style:TextStyle(color:Colors.amber,fontSize:20)),Text('238 rider reviews'),Text('Excellent service rating')]))]))),const SizedBox(height:15),...['Very polite and arrived quickly.','Clean car and safe driving.','Great communication at pickup.','Smooth trip, thank you!'].asMap().entries.map((e)=>Card(child:ListTile(leading:const CircleAvatar(child:Icon(Icons.person)),title:Text(['Asha S.','Juma O.','Fatma K.','Salma A.'][e.key]),subtitle:Text(e.value),trailing:const Text('★ 5.0',style:TextStyle(color:Colors.amber,fontWeight:FontWeight.bold))))) ]));}

class DocumentsScreen extends StatelessWidget{const DocumentsScreen({super.key});@override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('Documents')),body:ListView(padding:const EdgeInsets.all(18),children:[const Text('Verified documents are read-only. License and insurance can be renewed through an admin-reviewed request.'),const SizedBox(height:16),_doc(context,'Driver’s license','DL-ZNZ-884920','Expires 12 Mar 2027',true),_doc(context,'National ID','1995-02-22-12345','Verified • No expiry',false),_doc(context,'Vehicle insurance','INS-2026-8821','Expires 30 Nov 2026',true),_doc(context,'Vehicle photos','5 photos','Verified 14 Sep 2026',false),_doc(context,'Driver photo','Profile identity image','Verified 14 Sep 2026',false)]));
 Widget _doc(BuildContext c,String t,String n,String s,bool renew)=>Card(margin:const EdgeInsets.only(bottom:11),child:Padding(padding:const EdgeInsets.all(14),child:Row(children:[CircleAvatar(backgroundColor:ZenjiColors.green.withValues(alpha:.12),child:const Icon(Icons.verified_user_outlined,color:ZenjiColors.green)),const SizedBox(width:12),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(t,style:const TextStyle(fontWeight:FontWeight.w900)),Text(n),Text(s,style:TextStyle(fontSize:12,color:Theme.of(c).colorScheme.onSurface.withValues(alpha:.6)))])),if(renew)FilledButton.tonal(onPressed:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>RenewDocumentScreen(document:t))),child:const Text('Renew'))])));
}

class RenewDocumentScreen extends StatefulWidget{final String document;const RenewDocumentScreen({super.key,required this.document});@override State<RenewDocumentScreen> createState()=>_RenewDocumentScreenState();}
class _RenewDocumentScreenState extends State<RenewDocumentScreen>{String reason='Document expiring soon';bool uploaded=false;@override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:Text('Renew ${widget.document}')),body:ResponsivePage(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('Renewal request',style:Theme.of(context).textTheme.titleLarge?.copyWith(fontWeight:FontWeight.w900)),const SizedBox(height:8),const Text('The current document remains active until admin approves the replacement.'),const SizedBox(height:18),DropdownButtonFormField<String>(initialValue:reason,items:['Document expiring soon','Document expired','Updated / replaced document','Incorrect document on account','Other'].map((e)=>DropdownMenuItem(value:e,child:Text(e))).toList(),onChanged:(v)=>setState(()=>reason=v!),decoration:const InputDecoration(labelText:'Renew reason')),const SizedBox(height:14),Card(child:ListTile(leading:Icon(uploaded?Icons.check_circle:Icons.upload_file,color:uploaded?ZenjiColors.green:null),title:Text(uploaded?'New document attached':'Upload new document',style:const TextStyle(fontWeight:FontWeight.w800)),subtitle:Text(uploaded?'new_${widget.document.toLowerCase().replaceAll(' ','_')}.pdf':'PDF or clear image'),trailing:FilledButton.tonal(onPressed:()=>setState(()=>uploaded=true),child:Text(uploaded?'Replace':'Upload')))),const SizedBox(height:18),LoadingButton(label:'Submit renewal request',icon:Icons.send,onPressed:uploaded?()async{await fakeDelay();if(!context.mounted)return;await showDialog(context:context,builder:(d)=>AlertDialog(icon:const Icon(Icons.hourglass_top,color:ZenjiColors.green,size:42),title:const Text('Under review'),content:const Text('Your new document has been sent for admin verification. You will be notified if it is approved or rejected. Rejection includes a reason.'),actions:[FilledButton(onPressed:()=>Navigator.pop(d),child:const Text('Done'))]));if(context.mounted)Navigator.pop(context);}:null)])));
}

class SettingsScreen extends StatelessWidget{const SettingsScreen({super.key});@override Widget build(BuildContext context){final s=AppScope.of(context);final dark=Theme.of(context).brightness==Brightness.dark;return Scaffold(appBar:AppBar(title:const Text('Settings')),body:ResponsivePage(child:Column(children:[Card(child:SwitchListTile(value:dark,onChanged:s.toggleTheme,secondary:Icon(dark?Icons.dark_mode:Icons.light_mode),title:const Text('Dark mode',style:TextStyle(fontWeight:FontWeight.w800)),subtitle:const Text('Dark mode is the first-launch default.'))),const SizedBox(height:10),Card(child:Column(children:[RadioListTile<bool>(value:false,groupValue:s.isSwahili,onChanged:(v)=>s.setLanguage(v!),title:const Text('English')),RadioListTile<bool>(value:true,groupValue:s.isSwahili,onChanged:(v)=>s.setLanguage(v!),title:const Text('Kiswahili'))])),const SizedBox(height:10),const Card(child:SwitchListTile(value:true,onChanged:null,secondary:Icon(Icons.notifications_active_outlined),title:Text('Updates & offers',style:TextStyle(fontWeight:FontWeight.w800)),subtitle:Text('Enabled by default for this frontend demo.')))])));}}

class EmergencyScreen extends StatelessWidget{const EmergencyScreen({super.key});@override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('Emergency & support')),body:ResponsivePage(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Card(color:Colors.red.withValues(alpha:.08),child:ListTile(leading:const CircleAvatar(backgroundColor:Colors.redAccent,child:Icon(Icons.local_police,color:Colors.white)),title:const Text('Police emergency',style:TextStyle(fontWeight:FontWeight.w900)),subtitle:const Text('Call local emergency services immediately for urgent danger.'),trailing:FilledButton.tonal(onPressed:()=>toast(context,'Emergency dialer integration point'),child:const Text('Call')))),const SizedBox(height:16),const SectionTitle('ZenjiGO contact details'),const Card(child:Padding(padding:EdgeInsets.all(16),child:Column(children:[KeyValueRow('Phone','+255 676 891 227'),KeyValueRow('Email','zenjigo@support.com'),KeyValueRow('Instagram','@zenjigo')]))),const SizedBox(height:14),LoadingButton(label:'Open ZenjiGO in-app chat',icon:Icons.chat_bubble_outline,onPressed:()async{await fakeDelay(250);if(context.mounted)Navigator.push(context,MaterialPageRoute(builder:(_)=>const ChatScreen(name:'ZenjiGO Support',support:true)));})])));}
